config/routes.rb
Rails.application.routes.draw do
  resources :guests do
    post 'invite', on: :member
    get 'rsvp', on: :member
    post 'rsvp_update', on: :member
  end

  root 'guests#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def create
    @guest = Guest.new(guest_params)

    if @guest.save
      redirect_to @guest
    else
      render 'new'
    end
  end

  def update
    @guest = Guest.find(params[:id])

    if @guest.update(guest_params)
      redirect_to @guest
    else
      render 'edit'
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    redirect_to guests_path
  end

  def invite
    @guest = Guest.find(params[:id])
    GuestMailer.invite_email(@guest).deliver_now

    redirect_to guests_path
  end

  def rsvp
    @guest = Guest.find(params[:id])
  end

  def rsvp_update
    @guest = Guest.find(params[:id])

    if @guest.update(guest_params)
      flash[:notice] = "RSVP successful"
      redirect_to rsvp_guest_path(@guest)
    else
      render 'rsvp'
    end
  end

private
  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :email, :attending, :dietary_restrictions, :comments)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_with model: @guest, local: true do |form| %>
  <%= render 'form_errors' %>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :attending %><br>
    <%= form.check_box :attending %>
  </p>
  <p>
    <%= form.label :dietary_restrictions %><br>
    <%= form.text_field :dietary_restrictions %>
  </p>
  <p>
    <%= form.label :comments %><br>
    <%= form.text_field :comments %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/guests/_form_errors.html.erb
<% if @guest.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@guest.errors.count, "error") %> prohibited
      this guest from being saved:
    </h2>
    <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Edit Guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<h1>All guests:</h1>

<%= link_to 'Add guest', new_guest_path %>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Attending</th>
    <th>Dietary Restrictions</th>
    <th>Comments</th>
  </tr>

  <% @guests.each do |guest| %>
    <tr>
      <td><%= guest.first_name %></td>
      <td><%= guest.last_name %></td>
      <td><%= guest.email %></td>
      <td><%= guest.attending %></td>
      <td><%= guest.dietary_restrictions %></td>
      <td><%= guest.comments %></td>
      <td><%= link_to 'Show', guest_path(guest) %></td>
      <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
      <td><%= link_to 'Remove', guest_path(guest),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Send invite', invite_guest_path(guest),
              method: :post %></td>
    </tr>
  <% end %>
</table>

app/views/guests/new.html.erb
<h1>Add Guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/rsvp.html.erb
<h1>RSVP</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= form_for @guest, url: rsvp_update_guest_path(@guest), method: :post, local: true do |form| %>
  <%= render 'form_errors' %>

  <p>
    <%= form.label :attending %><br>
    <%= form.check_box :attending %>
  </p>
  <p>
    <%= form.label :dietary_restrictions %><br>
    <%= form.text_field :dietary_restrictions %>
  </p>
  <p>
    <%= form.label :comments %><br>
    <%= form.text_field :comments %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/guests/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @guest.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @guest.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<p>
  <strong>Attending:</strong>
  <%= @guest.attending %>
</p>

<p>
  <strong>Dietary Restrictions:</strong>
  <%= @guest.dietary_restrictions %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @guest.comments %>
</p>

<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rolo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>